# .github/workflows/ci.yml
name: dbt CI

on:
  pull_request:
    branches: [main, develop]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DBT_PROFILES_DIR: ${{ github.workspace }}
      GCLOUD_SA_KEY: ${{ secrets.GCP_SA_KEY }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dbt and dependencies
        run: |
          # Install only the dbt adapter and core
          pip install dbt-bigquery

      - name: Authenticate to GCP
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set quota project (fix ADC warning)
        run: gcloud auth application-default set-quota-project dotted-hulling-477021-d2

      - name: Install dbt packages
        run: dbt deps --target dev # This installs packages from packages.yml

      - name: dbt debug
        run: dbt debug --target dev

      - name: dbt compile (syntax check)
        run: dbt compile --target dev

      - name: dbt build (run + test)
        run: dbt build --target dev --fail-fast

      - name: Generate docs
        run: dbt docs generate --target dev

      - name: Upload docs artifact (optional)
        uses: actions/upload-artifact@v4
        with:
          name: dbt-docs
          path: target/